const AITHER_BACKEND='https://aitherbackendnew.onrender.com';
const grid=document.getElementById('gameGrid'),search=document.getElementById('search'),count=document.getElementById('count'),filters=document.getElementById('filters');
const recentGrid=document.getElementById('recentGrid'),emptyRecent=document.getElementById('emptyRecent'),originalsGrid=document.getElementById('originalsGrid');
let games=[],active='All',favoritesOnly=false;
const favKey='aither-gaming-favorites',recentKey='aither-gaming-recent',likesKey='aither-gaming-likes',dislikesKey='aither-gaming-dislikes';
const getSet=k=>new Set(JSON.parse(localStorage.getItem(k)||'[]'));const saveSet=(k,s)=>localStorage.setItem(k,JSON.stringify([...s]));
let favorites=getSet(favKey),recent=JSON.parse(localStorage.getItem(recentKey)||'[]'),likes=getSet(likesKey),dislikes=getSet(dislikesKey);
const accountButton=document.getElementById('accountButton'),accountModal=document.getElementById('accountModal'),accountLoggedOut=document.getElementById('accountLoggedOut'),accountLoggedIn=document.getElementById('accountLoggedIn'),accountForm=document.getElementById('accountForm'),accountName=document.getElementById('accountName'),accountEmail=document.getElementById('accountEmail'),accountPassword=document.getElementById('accountPassword'),accountSubmit=document.getElementById('accountSubmit'),accountMessage=document.getElementById('accountMessage'),accountWelcome=document.getElementById('accountWelcome'),accountEmailDisplay=document.getElementById('accountEmailDisplay'),accountVerifyStatus=document.getElementById('accountVerifyStatus'),accountSignedMessage=document.getElementById('accountSignedMessage'),resendVerification=document.getElementById('resendVerification'),logoutButton=document.getElementById('logoutButton');
let accountMode='login';
function authHeaders(){const token=localStorage.getItem('aither_session_token');return token?{Authorization:`Bearer ${token}`}:{}}
async function authRequest(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...authHeaders(),...(options.headers||{})};return fetch(`${AITHER_BACKEND}${path}`,{...options,headers,credentials:'include'})}
function showAccount(){accountModal.hidden=false;document.body.style.overflow='hidden'}function hideAccount(){accountModal.hidden=true;document.body.style.overflow=''}
function setAccountMode(mode){accountMode=mode;document.querySelectorAll('.account-tab').forEach(b=>b.classList.toggle('active',b.dataset.accountMode===mode));document.getElementById('nameField').hidden=mode!=='register';accountName.required=mode==='register';accountPassword.autocomplete=mode==='register'?'new-password':'current-password';accountSubmit.textContent=mode==='register'?'Create account':'Sign in';accountMessage.textContent=''}
function openAccount(user){showAccount();if(user){accountLoggedOut.hidden=true;accountLoggedIn.hidden=false;accountWelcome.textContent=`Welcome, ${user.name||'Aither user'}!`;accountEmailDisplay.textContent=user.email||'';accountVerifyStatus.textContent=user.email_verified?'Your email is verified and your Aither session is active.':'Your account is active. Please verify your email from the verification message.';resendVerification.style.display=user.email_verified?'none':'block'}else{accountLoggedOut.hidden=false;accountLoggedIn.hidden=true;setAccountMode('login')}}
async function refreshAccount(){try{const r=await authRequest('/api/auth/session');if(!r.ok)throw Error();const d=await r.json();if(d.authenticated&&d.user){accountButton.textContent=d.user.name?`Hi, ${d.user.name}`:'Account';return d.user}}catch(e){}accountButton.textContent='Account';return null}
accountButton.addEventListener('click',async()=>openAccount(await refreshAccount()));document.querySelectorAll('[data-close-account]').forEach(el=>el.addEventListener('click',hideAccount));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!accountModal.hidden)hideAccount()});document.querySelectorAll('.account-tab').forEach(b=>b.addEventListener('click',()=>setAccountMode(b.dataset.accountMode)));
accountForm.addEventListener('submit',async e=>{e.preventDefault();accountMessage.textContent='';accountSubmit.disabled=true;accountSubmit.textContent=accountMode==='register'?'Creating…':'Signing in…';try{const payload=accountMode==='register'?{name:accountName.value.trim(),email:accountEmail.value.trim(),password:accountPassword.value}:{email:accountEmail.value.trim(),password:accountPassword.value};const r=await authRequest(`/api/auth/${accountMode==='register'?'register':'login'}`,{method:'POST',body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Unable to complete account request.');if(d.session_token)localStorage.setItem('aither_session_token',d.session_token);accountPassword.value='';accountMessage.style.color='#8ff0ce';accountMessage.textContent=accountMode==='register'?'Account created! Check your email to verify it.':'Signed in successfully.';await refreshAccount();setTimeout(async()=>openAccount(d.user||await refreshAccount()),350)}catch(err){accountMessage.style.color='#ffb8c3';accountMessage.textContent=err.message||'Something went wrong.'}finally{accountSubmit.disabled=false;accountSubmit.textContent=accountMode==='register'?'Create account':'Sign in'}});
logoutButton.addEventListener('click',async()=>{logoutButton.disabled=true;try{await authRequest('/api/auth/logout',{method:'POST'})}catch(e){}localStorage.removeItem('aither_session_token');accountButton.textContent='Account';accountLoggedOut.hidden=false;accountLoggedIn.hidden=true;accountSignedMessage.style.color='#8ff0ce';accountSignedMessage.textContent='You are signed out.';setAccountMode('login');logoutButton.disabled=false});
resendVerification.addEventListener('click',async()=>{resendVerification.disabled=true;accountSignedMessage.style.color='#aeb6cc';accountSignedMessage.textContent='Sending verification email…';try{const r=await authRequest('/api/auth/verify/resend',{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Could not send verification email.');accountSignedMessage.style.color='#8ff0ce';accountSignedMessage.textContent=d.already_verified?'Your email is already verified.':'Verification email sent.'}catch(e){accountSignedMessage.style.color='#ffb8c3';accountSignedMessage.textContent=e.message}resendVerification.disabled=false});
function remember(path){recent=[path,...recent.filter(x=>x!==path)].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(recent))}
function react(path,type){if(type==='like'){likes.has(path)?likes.delete(path):(likes.add(path),dislikes.delete(path))}else{dislikes.has(path)?dislikes.delete(path):(dislikes.add(path),likes.delete(path))}saveSet(likesKey,likes);saveSet(dislikesKey,dislikes);render()}
function toggleFavorite(path){favorites.has(path)?favorites.delete(path):favorites.add(path);saveSet(favKey,favorites);render();renderRecent()}
function card(g){const f=favorites.has(g.path),l=likes.has(g.path),d=dislikes.has(g.path);return `<article class="game-card"><div class="card-actions"><button class="favorite ${f?'active':''}" data-fav="${escapeHtml(g.path)}" aria-label="${f?'Remove from':'Add to'} favorites">${f?'★':'☆'}</button><button class="reaction ${l?'active':''}" data-like="${escapeHtml(g.path)}" aria-label="Like">👍</button><button class="reaction ${d?'active dislike':''}" data-dislike="${escapeHtml(g.path)}" aria-label="Dislike">👎</button></div><a href="${g.path}/" data-play="${escapeHtml(g.path)}"><div class="game-icon">${g.icon||'🎮'}</div><h3>${escapeHtml(g.name)}</h3><p>${escapeHtml(g.category||'Games')}</p><span class="play">Play game →</span></a></article>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=search.value.trim().toLowerCase();const visible=games.filter(g=>(active==='All'||g.category===active)&&(!q||`${g.name} ${g.category}`.toLowerCase().includes(q))&&(!favoritesOnly||favorites.has(g.path)));count.textContent=`${visible.length} ${visible.length===1?'game':'games'} ready to play`;grid.innerHTML=visible.length?visible.map(card).join(''):`<div class="game-card" style="grid-column:1/-1;text-align:center"><h3>${favoritesOnly?'No favorites yet':'No games found'}</h3><p>${favoritesOnly?'Tap ☆ on a game to save it here.':'Try another search or category.'}</p></div>`;document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.fav)});document.querySelectorAll('[data-like]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();react(b.dataset.like,'like')});document.querySelectorAll('[data-dislike]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();react(b.dataset.dislike,'dislike')});document.querySelectorAll('[data-play]').forEach(a=>a.addEventListener('click',()=>remember(a.dataset.play)))}
function renderRecent(){const picks=recent.map(p=>games.find(g=>g.path===p)).filter(Boolean).slice(0,8);document.getElementById('favoriteCount').textContent=`${favorites.size} FAVORIT${favorites.size===1?'E':'ES'}`;recentGrid.innerHTML=picks.map(g=>`<a class="mini-card" href="${g.path}/" data-play="${escapeHtml(g.path)}"><span class="mini-icon">${g.icon||'🎮'}</span><div><strong>${escapeHtml(g.name)}</strong><span>Recently played</span></div></a>`).join('');emptyRecent.style.display=picks.length?'none':'block'}
function renderOriginals(){const originals=games.filter(g=>g.category==='AI Originals'||String(g.path).includes('/ai-')).slice(0,10);originalsGrid.innerHTML=originals.map(g=>`<a class="mini-card" href="${g.path}/"><span class="mini-icon">${g.icon||'🤖'}</span><div><strong>${escapeHtml(g.name)}</strong><span>Aither Original</span></div></a>`).join('')}
function spotlight(){if(!games.length)return;const g=games[Math.floor(Math.random()*games.length)];document.getElementById('spotlightName').textContent=g.name;document.getElementById('spotlightMeta').textContent=`${g.icon||'🎮'} ${g.category||'Games'} • Ready to play`;document.getElementById('spotlightPlay').onclick=()=>{remember(g.path);location.href=`cdn-player.html?game=${encodeURIComponent(g.path)}`}}
function setupSuggestions(){const form=document.getElementById('suggestionForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const file=document.getElementById('suggestFile').files[0];const item={name:document.getElementById('suggestName').value.trim(),url:document.getElementById('suggestUrl').value.trim(),reason:document.getElementById('suggestReason').value.trim(),code:document.getElementById('suggestCode').value,filename:file?.name||'',future:document.getElementById('suggestAgain').value,created:new Date().toISOString()};const list=JSON.parse(localStorage.getItem('aither-game-suggestions')||'[]');list.push(item);localStorage.setItem('aither-game-suggestions',JSON.stringify(list));const msg=document.getElementById('suggestMessage');msg.style.color='#8ff0ce';msg.textContent=file?'Suggestion saved on this device, including the selected file name.':'Suggestion saved on this device.';form.reset()});document.getElementById('clearSuggestion')?.addEventListener('click',()=>form.reset());document.querySelectorAll('[data-survey]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('aither-suggestion-survey',b.dataset.survey);document.getElementById('surveyMessage').textContent='Thanks for the feedback!'}))}
async function init(){try{const [mainResponse,aiResponse]=await Promise.all([fetch('games.json',{cache:'no-store'}),fetch('ai-games.json',{cache:'no-store'})]);if(!mainResponse.ok)throw Error('games.json failed');games=await mainResponse.json();if(aiResponse.ok){const ai=await aiResponse.json(),existing=new Set(games.map(g=>g.path));games=[...games,...ai.filter(g=>!existing.has(g.path))]}document.getElementById('heroCount').textContent=games.length;const categories=['All',...new Set(games.map(g=>g.category).filter(Boolean))];filters.innerHTML=categories.map(c=>`<button class="chip ${c==='All'?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');filters.addEventListener('click',e=>{const b=e.target.closest('.chip');if(!b)return;active=b.dataset.category;favoritesOnly=false;document.getElementById('favoritesToggle').classList.remove('active');document.querySelectorAll('#filters .chip').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('favoritesToggle').addEventListener('click',()=>{favoritesOnly=!favoritesOnly;document.getElementById('favoritesToggle').classList.toggle('active',favoritesOnly);render()});search.addEventListener('input',render);render();renderRecent();renderOriginals();spotlight();setupSuggestions();await refreshAccount()}catch(e){count.textContent='Game library failed to load'}}
const themeButton=document.getElementById('themeButton'),saved=localStorage.getItem('aither-theme');if(saved==='light')document.body.classList.add('light');themeButton.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('aither-theme',document.body.classList.contains('light')?'light':'dark')};init();
