const games=[
 {name:'Candy Crush',icon:'🍬',category:'Puzzle',path:'01-Candy-Crush-Game'},
 {name:'Archery',icon:'🏹',category:'Action',path:'02-Archery-Game'},
 {name:'Minesweeper',icon:'💣',category:'Puzzle',path:'05-Minesweeper-Game'},
 {name:'Tower Blocks',icon:'🏗️',category:'Arcade',path:'06-Tower-Blocks'},
 {name:'Tetris',icon:'🟦',category:'Puzzle',path:'08-Tetris-Game'},
 {name:'Tilting Maze',icon:'🌀',category:'Puzzle',path:'09-Tilting-Maze-Game'},
 {name:'Rock Paper Scissors',icon:'✊',category:'Party',path:'11-Rock-Paper-Scissors'},
 {name:'Number Guessing',icon:'🔢',category:'Puzzle',path:'12-Type-Number-Guessing-Game'},
 {name:'Connect Four',icon:'🔴',category:'Board',path:'15-Connect-Four-Game'},
 {name:'Hangman',icon:'🔤',category:'Word',path:'18-Hangman-Game'},
 {name:'Crossy Road',icon:'🐔',category:'Arcade',path:'20-Crossy-Road-Game'},
 {name:'2048',icon:'🔢',category:'Puzzle',path:'21-2048-Game'},
 {name:'10 Minutes Till Dawn',icon:'🌅',category:'Action',ugs:'10minutestilldawn'},
 {name:'2 Minute Football',icon:'🏈',category:'Sports',ugs:'2 minute football'},
 {name:'2-3-4 Player Games',icon:'👥',category:'Multiplayer',ugs:'2-3-4-player-game'},
 {name:'2Doom',icon:'💀',category:'Action',ugs:'2doom'},
 {name:'3Dash',icon:'🔺',category:'Arcade',ugs:'3dash'},
 {name:'Antimatter Dimensions',icon:'⚛️',category:'Strategy',ugs:'Antimatter Dimensions'},
 {name:'Adventure Capitalist',icon:'💰',category:'Strategy',ugs:'adventure-capitalist'},
 {name:'Ages of Conflict',icon:'🌍',category:'Strategy',ugs:'ages of conflict'},
 {name:'Airline Tycoon Idle',icon:'✈️',category:'Strategy',ugs:'airline-tycoon-idle'},
 {name:'Alien Sky Invasion',icon:'👽',category:'Action',ugs:'alien sky invasion'},
 {name:'Amazing Strange Rope Police',icon:'🕷️',category:'Action',ugs:'amazing-strange-rope-police-vice-spider'},
 {name:'Amidst the Sky',icon:'☁️',category:'Arcade',ugs:'amidst the sky'},
 {name:'Angry Birds',icon:'🐦',category:'Action',ugs:'angry-bird'},
 {name:'Apes vs Helium',icon:'🐒',category:'Action',ugs:'apesvshelium'},
 {name:'Arcade Volley',icon:'🏐',category:'Sports',ugs:'arcade-volley'},
 {name:'Astro Survivors',icon:'🚀',category:'Action',ugs:'astro survivors'},
 {name:'Aviamasters',icon:'✈️',category:'Sports',ugs:'aviamaster'},
 {name:'Babel Tower',icon:'🗼',category:'Arcade',ugs:'babel tower'},
 {name:'Backrooms 2D',icon:'🚪',category:'Adventure',ugs:'backrooms 2D'},
 {name:'Bacon May Die',icon:'🥓',category:'Action',ugs:'bacon may die'},
 {name:'Bad Parenting',icon:'😈',category:'Adventure',ugs:'bad-parenting'},
 {name:'Baldi’s Basics',icon:'📚',category:'Adventure',ugs:'baldis-basics'},
 {name:'Ballistic',icon:'🎯',category:'Action',ugs:'ballistic'},
 {name:'Banana Poker',icon:'🍌',category:'Card',ugs:'banana poker'},
 {name:'Barry Has a Secret',icon:'🕵️',category:'Adventure',ugs:'barry has a secret'},
 {name:'Baseball Bros',icon:'⚾',category:'Sports',ugs:'baseball bros'},
 {name:'Basket Stars',icon:'🏀',category:'Sports',ugs:'basket stars'},
 {name:'Basketball Superstars',icon:'🏀',category:'Sports',ugs:'basketball-superstars'},
 {name:'Beach Boxing Simulator',icon:'🥊',category:'Sports',ugs:'beach-boxing-sim'},
 {name:'Bearsus',icon:'🐻',category:'Action',ugs:'bearsus'},
 {name:'Ben 10 Super Slammer',icon:'👊',category:'Action',ugs:'ben 10 super slammer'},
 {name:'Big Flappy Tower',icon:'🐤',category:'Arcade',ugs:'big flappy tower'},
 {name:'Block Miner',icon:'⛏️',category:'Arcade',ugs:'block-miner'},
 {name:'Blockpost',icon:'🔫',category:'Action',ugs:'blockpost'},
 {name:'Blumgi Racers',icon:'🏎️',category:'Racing',ugs:'blumgi racers'},
 {name:'Blumgi Rocket',icon:'🚀',category:'Racing',ugs:'blumgi-rocket'},
 {name:'Bounce Back',icon:'↩️',category:'Arcade',ugs:'bounce back'},
 {name:'Bouncy Basketball',icon:'🏀',category:'Sports',ugs:'bouncy basketball'},
 {name:'Bounty of One',icon:'🤠',category:'Action',ugs:'bounty of one'},
 {name:'Bullet Force Multiplayer',icon:'🎯',category:'Action',ugs:'bullet-force-multiplayer'},
 {name:'Capybara Clicker',icon:'🦫',category:'Idle',ugs:'capybara clicker'},
 {name:'Cat Mario',icon:'🐱',category:'Platformer',ugs:'cat mario'},
 {name:'Cats Love Cake 2',icon:'🐈',category:'Platformer',ugs:'cats love cake 2'},
 {name:'Cave Chaos 2',icon:'🕳️',category:'Action',ugs:'cave chaos 2'},
 {name:'Cheese Chompers 3',icon:'🧀',category:'Arcade',ugs:'cheese chompers 3'},
 {name:'Chicken Gun',icon:'🐔',category:'Action',ugs:'chicken-gun'},
 {name:'Choppy Orc',icon:'🪓',category:'Action',ugs:'choppy orc'},
 {name:'CircloO 2',icon:'⭕',category:'Arcade',ugs:'circlo02'},
 {name:'Clash of Vikings',icon:'⚔️',category:'Strategy',ugs:'clashofvikings'},
 {name:'Cookie Clicker',icon:'🍪',category:'Idle',ugs:'cookieclicker'},
 {name:'Crazy Cars',icon:'🚗',category:'Racing',ugs:'crazy cars'},
 {name:'Crazy Chicken 3D',icon:'🐔',category:'Action',ugs:'crazy chicken 3D'},
 {name:'Creature Card Idle',icon:'🃏',category:'Idle',ugs:'creature-card-idle'},
 {name:'CSGO Surf',icon:'🏄',category:'Skill',ugs:'csgo surf'},
 {name:'Dandy’s World Clicker',icon:'🖱️',category:'Idle',ugs:'dandys-world-clicker'},
 {name:'Deepest Sword',icon:'⚔️',category:'Adventure',ugs:'deepest sword'},
 {name:'Die in the Dungeon',icon:'🏰',category:'Strategy',ugs:'die in the dungeon'},
 {name:'Doge Miner 2',icon:'🐕',category:'Idle',ugs:'doge miner 2'},
 {name:'Doodle Jump',icon:'🦘',category:'Arcade',ugs:'doodle jump'},
 {name:'Down the Mountain',icon:'⛰️',category:'Arcade',ugs:'down the mountain'},
 {name:'Drift Hunters',icon:'🏎️',category:'Racing',ugs:'drift-hunters'},
 {name:'Drunken Duel',icon:'🤠',category:'Action',ugs:'drunken duel'},
 {name:'Duck Life 6',icon:'🦆',category:'Sports',ugs:'duck life 6'},
 {name:'Duck Life Battle',icon:'🦆',category:'Action',ugs:'duck life battle'},
 {name:'Dungeon Deck',icon:'🃏',category:'Strategy',ugs:'dungeondeck'},
 {name:'Eagle Ride',icon:'🦅',category:'Arcade',ugs:'eagle ride'},
 {name:'Eggy Car',icon:'🥚',category:'Racing',ugs:'eggy car'},
 {name:'Elastic Man',icon:'😜',category:'Arcade',ugs:'elasticman'},
 {name:'Five Nights at Osaka’s',icon:'🌙',category:'Horror',ugs:'Five Nights at Osaka\'s'},
 {name:'Football Bros',icon:'⚽',category:'Sports',ugs:'football bros'},
 {name:'Fork n Sausage',icon:'🌭',category:'Puzzle',ugs:'fork-n-sausage'},
 {name:'Fortzone Battle Royale',icon:'🏝️',category:'Action',ugs:'fortzone battle royale'},
 {name:'Freegemas',icon:'💎',category:'Puzzle',ugs:'freegemas'},
 {name:'Funny Shooter 2',icon:'🔫',category:'Action',ugs:'funny shooter 2'},
 {name:'Golf Orbit',icon:'⛳',category:'Sports',ugs:'golf orbit'},
 {name:'Granny 3',icon:'👵',category:'Horror',ugs:'granny 3'},
 {name:'Mad Stick',icon:'🥷',category:'Action',ugs:'mad stick'},
 {name:'Melon Playground',icon:'🍉',category:'Sandbox',ugs:'melon playground'},
 {name:'Mine Shooter',icon:'⛏️',category:'Action',ugs:'mine shooter'},
 {name:'Mini Shooters',icon:'🎯',category:'Action',ugs:'mini shooters'},
 {name:'Monkey Mart',icon:'🐒',category:'Simulation',ugs:'monkey mart'},
 {name:'Moto X3M',icon:'🏍️',category:'Racing',ugs:'motox3m'},
 {name:'Mountain Bike Racer',icon:'🚵',category:'Racing',ugs:'mountain bike racer'},
 {name:'MX Offroad Master',icon:'🏍️',category:'Racing',ugs:'mx offroad master'},
 {name:'Neon Blaster',icon:'🔵',category:'Action',ugs:'neon blaster'},
 {name:'Neverending Legacy',icon:'🏰',category:'Strategy',ugs:'neverending legacy'},
 {name:'Ninja Obby Parkour',icon:'🥷',category:'Platformer',ugs:'ninja obby parkour'},
 {name:'Noob Miner',icon:'⛏️',category:'Adventure',ugs:'noob miner'}
];
const base='https://aa-gamerz22.github.io/aa-gamerz-games/';
const ugsBase='https://cdn.jsdelivr.net/gh/bubbls/UGS-Assets@main/';
const grid=document.getElementById('gameGrid'),search=document.getElementById('search'),count=document.getElementById('count'),filters=document.getElementById('filters');
let active='All';
const categories=['All',...new Set(games.map(g=>g.category))];
filters.innerHTML=categories.map(c=>`<button class="chip ${c==='All'?'active':''}" data-category="${c}">${c}</button>`).join('');
filters.addEventListener('click',e=>{const b=e.target.closest('.chip');if(!b)return;active=b.dataset.category;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});
search.addEventListener('input',render);
function gameUrl(g){return g.ugs?`${ugsBase}${encodeURI(g.ugs)}/index.html`:`${base}${g.path}/`;}
function render(){const q=search.value.trim().toLowerCase();const visible=games.filter(g=>(active==='All'||g.category===active)&&(!q||`${g.name} ${g.category}`.toLowerCase().includes(q)));count.textContent=`${visible.length} games ready to play`;grid.innerHTML=visible.length?visible.map(g=>{const href=gameUrl(g);return `<a class="game-card" href="${href}" target="_blank" rel="noopener"><div class="game-icon">${g.icon}</div><h3>${g.name}</h3><p>${g.category}</p><span class="play">Play game →</span></a>`}).join(''):`<div class="game-card" style="grid-column:1/-1;text-align:center"><h3>No games found</h3><p>Try another search or category.</p></div>`}
const themeButton=document.getElementById('themeButton');const saved=localStorage.getItem('aither-theme');if(saved==='light')document.body.classList.add('light');themeButton.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('aither-theme',document.body.classList.contains('light')?'light':'dark')};render();